### ISSUE TITLE
请问自带支持https吗

### ISSUE THREAD

**Issue by xzhixian** [yanzhenjie/NoHttp#1]

**Comment by Y0LANDA** [comment]
你好，支持标准的https协议，在demo中也有https的例子的，在ReadMe中有我博客的地址，我的这篇博客对Android的https做了详细的解释：http://blog.csdn.net/yanzhenjie1003/article/details/50731272

**Comment by xzhixian** [comment]
请问如果网络超时的情况下，由于ui显示方面不希望直接就一个空白页，我想先拿到之前的缓存来显示，然后再等数据或者304回来再更新，我应该从哪个地方开始去改代码。

**Comment by xzhixian** [comment]
大神加油 加油 这个真的是业务刚需 @Y0LANDA

**Comment by Y0LANDA** [comment]
多谢你的执行hi，目前这个方法没有对外开放，我接下来马上开放这个接口。你用Tencent QQ吗？如果用的话加一下我在ReadMe中公布的QQ群。
