### ISSUE TITLE
NoHttp.getDownloadQueueInstance()添加的下载任务，进度回调一部分后，就没有回调了，其实文件正在下载中

### ISSUE THREAD

**Issue by liajt** [yanzhenjie/NoHttp#102]
06-23 16:05:13.250 28056-28056/com.led.player I/MyDownLoadService: onProgress： progress:41 fileCount:2092560 speed:612168
06-23 16:05:13.300 28056-28056/com.led.player I/MyDownLoadService: onProgress： progress:42 fileCount:2105720 speed:612168
06-23 16:05:13.350 28056-28056/com.led.player I/MyDownLoadService: onProgress： progress:43 fileCount:2161412 speed:612168
06-23 16:05:13.460 28056-28056/com.led.player I/MyDownLoadService: onProgress： progress:44 fileCount:2206024 speed:612168
06-23 16:05:13.530 28056-28056/com.led.player I/MyDownLoadService: onProgress： progress:45 fileCount:2260608 speed:612168
06-23 16:05:13.560 28056-28056/com.led.player I/MyDownLoadService: onProgress： progress:45 fileCount:2284896 speed:636874
06-23 16:05:13.610 28056-28056/com.led.player I/MyDownLoadService: onProgress： progress:46 fileCount:2309468 speed:636874
06-23 16:05:13.700 28056-28056/com.led.player I/MyDownLoadService: onProgress： progress:47 fileCount:2357088 speed:636874

**Comment by gallonyin** [comment]
@liajt 
如果你是在调用方法上使用DownloadListener的匿名内部类，那么你可以先尝试将 DownloadListener downloadListener 做为成员内部类。
该问题原因是 DownloadRequest 持有 downloadListener 加上了弱引用包裹，你的回调监听被回收了

**Comment by yanzhenjie** [comment]
现在把这个弱引用取消了，应该没问题了。
