### ISSUE TITLE
找不到1.1.3的版本

### ISSUE THREAD

**Issue by luoqqsh** [yanzhenjie/NoHttp#103]
compile 'com.yanzhenjie.nohttp:nohttp:1.1.3'

Error:Failed to resolve: Could not resolve com.yanzhenjie.nohttp:nohttp:1.1.3.
Required by:
    project :app
<a href="disable.gradle.offline.mode">Disable offline mode and sync project</a><br><a href="openFile:/Users/gxxing/Documents/zuoye/MC/app/build.gradle">Open File</a>

1.1.2的版本可以用

**Comment by yanzhenjie** [comment]
应该有的吧，现在是1.1.5了。
