### ISSUE TITLE
multipart/form-data 怎么写

### ISSUE THREAD

**Issue by caoyuliang0225** [yanzhenjie/NoHttp#115]
RequestBody中需要把 file的路径，file的文件名，和file作为一个part发送到服务器。但是我只找到了file+file名的方法，由于服务器不是自家的，不能改动，需要我这边改，却不知道如何更改。希望能得到指点。
例如，类似以下的事例代码：
MultipartBody.Builder builder = new MultipartBody.Builder().setType(MultipartBody.FORM);
RequestBody fileBody = RequestBody.create(MediaType.parse("multipart/form-data"), file);
builder.addFormDataPart(file.getPath(), file.getName(), fileBody);
List<MultipartBody.Part> parts = builder.build().parts();

**Comment by yanzhenjie** [comment]
你上面的代码其实有点问题，`addFormDataPart()`有两个重载：
```
addFormDataPart(String name, String value);
addFormDataPart(String name, String filename, RequestBody body);
```
第一个方法中，第一个参数是form的某一般item的key，第二个参数是form的某一般item的value。  
第二个方法中，第一个参数是form的某文件item的key，第二个参数是某文件item的name，第三个参数是file。因为文件item中的**文件**不是特指（File对象），它可以是流、字节数组、File对象、在Android的Bitmap等等，所以它是RequestBody（NoHttp中它叫Binary，有多种实现，开发者也可以自己实现）。

说你的有点问题的意思是，你的key貌似传了File的path，不知道你服务器是不是允许key随便传，也就是说不要求特定key。

----

转为NoHttp的话，以请求String为例：
```
StringRequest stringRequest = new StringRequest(url, RequestMethod.POST);
stringRequest.add(key, new FileBinary(new File(filePath)));
```
添加File即可，剩下的会自动完成，对于key，你可以像你原代码一样传path，也可以随意传一个非null/""的字符串，如果服务器要求key是定的，比如“userHeader”，那么你传服务器指定的key即可。
