### ISSUE TITLE
严大，请教下，nohttp的同步是不是长效连接啊？

### ISSUE THREAD

**Issue by wjy591416** [yanzhenjie/NoHttp#116]
我原来是在Executors中封装的网络请求，之前您说nohttp的同步请求，可替代一般的网络请求，所有我替换了，可是现在问题出来了，
我 的app是用在学校局域网中，一台服务器，服务于多个终端。在用原来的网络请求的时候，可以连接50多台设备，运行效率还是可以的。但是，现在替换成以okhttp为底层的nohttp同步请求后，只能连接5台设备，在多连接就明显感觉数据获取速度变慢

**Comment by yanzhenjie** [comment]
抱歉回复的迟了，希望还能帮助到你。  
NoHttp的异步请求也是基于同步请求封装的，异步请求只是切换了线程，即不在当前调用的线程发起请求，而是在一个子线程中发起请求。  
另外NoHttp的异步请求有队列（RequestQueue），异步请求执行器（AsynsRequestExecutor），前者可以规定它的线程数量，默认是3个，后者是线程池。这样就会存在并发执行，也是影响服务器性能的一个方面，但是可以忽略不计。

关于长连接，Http其实是短连接，即握手后就松开，用Cookie来保持会话状态。但是Http也是基于Socket的，如果我们添加了`Connection`头为`keep-alive`，那么服务器可能会保持连接（服务器软件有一个连接池，大小可配置，比如tomcat、nginx）来提高客户端下次请求时的响应速度，当保持连接的客户端多了服务器会自动断开队列最前方连接的客户端（越靠前使用频率越低，上次使用时与当前时间的间隔越大）。

Http1.0中要想保持连接需要客户端主动添加`Connection`头为`keep-alive`，Http1.1中默认就是保持连接的。如果需要禁止保持连接，把值改为`close`即可。NoHttp默认添加了保持连接的头（为了兼容Http1.0）。

希望可以帮助到你。
