### ISSUE TITLE
android设备通过网线连接内网访问内网服务器提示无网络可用

### ISSUE THREAD

**Issue by yanjiaxue** [yanzhenjie/NoHttp#117]
有没有哪位大神知道什么原因？谢谢

**Comment by yanzhenjie** [comment]
是Android板卡吗？你可以自己找个工具类看看不是有网络，如果是NoHttp判断有误，我快尽快更新。

**Comment by imknown** [comment]
https://github.com/yanzhenjie/NoHttp/blob/3ad5f2eb9c989defac6e51fdf4b61aab5ef38801/nohttp/src/main/java/com/yanzhenjie/nohttp/tools/NetUtils.java#L136

这个??

**Comment by yanjiaxue** [comment]
十分抱歉，实施那边反馈过来的问题描述错了，十分抱歉，不是NoHttp的问题，也多谢你们的回答，谢谢

**Comment by yanjiaxue** [comment]
@yanzhenjie @imknown  十分抱歉，实施那边反馈过来的问题描述错了，十分抱歉，不是NoHttp的问题，也多谢你们的回答，谢谢

**Comment by imknown** [comment]
那是啥错误啊... 一脸懵逼
