### ISSUE TITLE
java.lang.NullPointerException

### ISSUE THREAD

**Issue by shiwobuhaoma** [yanzhenjie/NoHttp#118]
Attempt to invoke interface method 'boolean java.util.List.add(java.lang.Object)' on a null object reference

2 com.yanzhenjie.nohttp.tools.BasicMultiValueMap.add(BasicMultiValueMap.java)
3 com.yanzhenjie.nohttp.tools.BasicMultiValueMap.set(BasicMultiValueMap.java)
4 com.yanzhenjie.nohttp.HttpHeaders.setAll(HttpHeaders.java)
5 com.yanzhenjie.nohttp.rest.RestProtocol.analysisCacheAndProtocol(RestProtocol.java)
6 com.yanzhenjie.nohttp.rest.RestProtocol.request(RestProtocol.java)
7 com.yanzhenjie.nohttp.rest.SyncRequestExecutor.execute(SyncRequestExecutor.java)
8 com.yanzhenjie.nohttp.rest.RequestDispatcher.run(RequestDispatcher.java)

**Comment by yanzhenjie** [comment]
收到，会尽快修复。

**Comment by xicong** [comment]
大佬，这个问题出现很多次了，什么时候可以更新下啊

**Comment by 158323** [comment]
出现N次，年终奖快保不住了

**Comment by yanzhenjie** [comment]
确认有这个问题，汇总到 #147  。
