### ISSUE TITLE
java.lang.OutOfMemoryError 

### ISSUE THREAD

**Issue by shiwobuhaoma** [yanzhenjie/NoHttp#122]
com.yanzhenjie.nohttp.tools.IOUtils.write(IOUtils.java)

1 java.io.ByteArrayOutputStream.expand(ByteArrayOutputStream.java:91)
--
2 java.io.ByteArrayOutputStream.write(ByteArrayOutputStream.java:201)
3 com.yanzhenjie.nohttp.tools.IOUtils.write(IOUtils.java)
4 com.yanzhenjie.nohttp.tools.IOUtils.toByteArray(IOUtils.java)
5 com.yanzhenjie.nohttp.rest.RestProtocol.getHttpProtocol(RestProtocol.java)
6 com.yanzhenjie.nohttp.rest.RestProtocol.requestCacheOrNetwork(RestProtocol.java)
7 com.yanzhenjie.nohttp.rest.RestProtocol.request(RestProtocol.java)
8 com.yanzhenjie.nohttp.rest.SyncRequestExecutor.execute(SyncRequestExecutor.java)
9 com.yanzhenjie.nohttp.rest.RequestDispatcher.run(RequestDispatcher.java)

**Comment by yanzhenjie** [comment]
麻烦把调用的代码贴一下。

**Comment by lby1992** [comment]
Did you forget to free the memory allocation somewhere?

**Comment by shiwobuhaoma** [comment]
bugly给的就这么多错误信息，具体是哪里的问题，我也不太清楚

**Comment by shiwobuhaoma** [comment]
@yanzhenjie bugly给的就这么多错误信息，具体是哪里的问题，我也不太清楚

**Comment by shiwobuhaoma** [comment]
@yanzhenjie 又看了下使用文档，我确实没有做过queue.stop();的操作，估计就是这个原因吧
