### ISSUE TITLE
使用中比较容易出现的一个错误

### ISSUE THREAD

**Issue by lgxok** [yanzhenjie/NoHttp#127]
E/xxx-NoHttp(22224): java.io.EOFException
E/xxx-NoHttp(22224): 	at libcore.io.Streams.readAsciiLine(Streams.java:203)
E/xxx-NoHttp(22224): 	at libcore.net.http.HttpEngine.readResponseHeaders(HttpEngine.java:579)
E/xxx-NoHttp(22224): 	at libcore.net.http.HttpEngine.readResponse(HttpEngine.java:827)
E/xxx-NoHttp(22224): 	at libcore.net.http.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:283)
E/xxx-NoHttp(22224): 	at libcore.net.http.HttpURLConnectionImpl.getResponseCode(HttpURLConnectionImpl.java:497)
E/xxx-NoHttp(22224): 	at com.yanzhenjie.nohttp.URLConnectionNetwork.getResponseCode(Proguard:48)
E/xxx-NoHttp(22224): 	at com.yanzhenjie.nohttp.HttpConnection.getConnection(Proguard:79)
E/xxx-NoHttp(22224): 	at com.yanzhenjie.nohttp.rest.RestProtocol.getHttpProtocol(Proguard:160)
E/xxx-NoHttp(22224): 	at com.yanzhenjie.nohttp.rest.RestProtocol.requestCacheOrNetwork(Proguard:122)
E/xxx-NoHttp(22224): 	at com.yanzhenjie.nohttp.rest.RestProtocol.request(Proguard:59)
E/xxx-NoHttp(22224): 	at com.yanzhenjie.nohttp.rest.SyncRequestExecutor.execute(Proguard:41)
E/xxx-NoHttp(22224): 	at com.yanzhenjie.nohttp.NoHttp.startRequestSync(Proguard:335)

**Comment by yanzhenjie** [comment]
一般是因为局域网网络不稳定，服务器不稳定。
