### ISSUE TITLE
如何实现多个文件上传并显示进度呢？

### ISSUE THREAD

**Issue by excellenttank** [yanzhenjie/NoHttp#13]
显示每个文件的进度，可以让未上传的出去等待状态

**Comment by excellenttank** [comment]
显示每个文件的进度

**Comment by yanzhenjie** [comment]
@excellenttank 一共有三个方案。
一、开放了Binary接口，这个接口你可以自己实现，进度也可以自己通知。

二、NoHttp其实 已经提供了默认的Binary接口实现，如FileBinary、InputStreamBinary、BitmapBinary、ByteArrayBinary、按照自己的开发需求用。这个几个实现都已经提供了默认的进度回调，`binary.setUploadHandler`。

三、上述四个上传实现都是继承与BasicBinary类，BisicBinary类是实现了Binary接口的。如果你不想自己实现Binary接口，那么你可以继承BisicBinary类，来定义自己的文件上传实现。

**Comment by tianshaokai** [comment]
作者最好可以在demo 中写个多文件上传显示状态的例子

**Comment by yanzhenjie** [comment]
@tianshaokai 这个已经写了啊，多文件上传更新ui。再说了进度的接口有了，更下下ui不是炒鸡简单呀！嘿嘿。

**Comment by tianshaokai** [comment]
@yanzhenjie 嗯嗯开源库只要是傻瓜式的，demo 也是傻瓜式的，我相信会比okhttp 更厉害，更屌
