### ISSUE TITLE
URISyntaxException

### ISSUE THREAD

**Issue by xicong** [yanzhenjie/NoHttp#130]
遇到一个这种异常，查资料好像说是url里面有特殊字符，nohttp是不是没做这个兼容啊

**Comment by yanzhenjie** [comment]
path中如果如果又特殊字符，NoHttp不会自动处理，你可以自己拼接Path，NoHttp也提供了方便的方法。  
比如你的链接是：    
> `http://www.example.com/tv/三国演义/userList?user=admin&password=123`

那么我们可以这样拼接：
```java
Request<String> request = new StringRequest("http://www.example.com/tv");
request.path(URLCoder.encode("三国演义"))
    .path("userList")
    .add("user", "admin")
    .add("password", 123);
```

> 比如URL中有中文参数也需要用`add(String, String)`方法添加，不能直接跟在URL后面。

当然path的用处还有很多，比如服务器的rest地址是：
> `http://www.example.com/tv/{tvname}/userList`

那么这种需要补全的时候就可以用到`path`方法了。
