### ISSUE TITLE
重定向后，请求里的header值有重复

### ISSUE THREAD

**Issue by pcddyl** [yanzhenjie/NoHttp#132]
默认的重定向处理流程：
先new 一个 BasicRequest，初始化时会增加默认的ua、Accept等，
然后将oldRequest的header添加到新的Request，由于header的值是list，会造成ua、accept等值会是重复的，或者和原始请求里的不一致。

**Comment by yanzhenjie** [comment]
嗯，刚看了代码确实存在这个问题。

**Comment by yanzhenjie** [comment]
刚发布了1.1.5版本，修复了这个问题。
