### ISSUE TITLE
请求头

### ISSUE THREAD

**Issue by jksfood** [yanzhenjie/NoHttp#136]

**Comment by jksfood** [comment]
sorry，i  need help。
when i use nohttp on android 4.4 , i use get method , 请求头中包含了中文字符，但是貌似产生了乱码，但是在5.0以上的系统中就没有这个问题。please help me.
![image](https://user-images.githubusercontent.com/8231502/33019602-fedcf0e6-ce35-11e7-80d4-6bc7ff559dc5.png)

![image](https://user-images.githubusercontent.com/8231502/33019626-180ba60c-ce36-11e7-832d-19054b31afbb.png)

**Comment by yanzhenjie** [comment]
建议使用`OkHttp`作为底层，添加`Header`时对`Value`做`URLEncoder`：
```java
request.addHeader("name", URLEncoder.encode("我是一个粉刷匠", "utf-8"));
```
当然上述代码会编译时异常，需要`try catch`，所以你可以写一个帮助类：
```java
public class URLCoder {
    public static String encode(String content, String charset) {
        try {
            return URLEncoder.encode(content, charset);
        } catch (UnsupportedEncodingException e) {
            return content;
        }
    }

    public static String decode(String content, String charset) {
        try {
            return URLDecoder.decode(content, charset);
        } catch (UnsupportedEncodingException e) {
            return content;
        }
    }
}
```
不过看你截图似乎是表单抓到的内容乱码，不知道提交到服务器是否正常，我公司App使用`OkHttp`作为`NoHttp`底层，在任何手机上都没有出现上述问题。

**Comment by jksfood** [comment]
![qq 20171121090941](https://user-images.githubusercontent.com/8231502/33049624-fb2191e4-ce9b-11e7-9004-be64fae1d47c.png)

这样就可以了，谢谢。不明觉厉，为什么直接拼写在URL后面就有问题
