### ISSUE TITLE
在onResume中请求网络，一段时间后回到前台，提示无网络

### ISSUE THREAD

**Issue by guangxingmao** [yanzhenjie/NoHttp#138]
严哥，我在onResume中请求网络，局部刷新数据，在将app退至后台后，一段时间再回到前台，会提示无网络，但是我网络是正常的，于是刚刚测试了Nohttp的sample,也同样遇到了这个问题，我的手机是小米mix2，使用retrofit等框架均无问题
[onResume中的代码](http://opn79542e.bkt.clouddn.com/3D2545767F8C2CD7C3D71AC570073170.png)
[Nohttpdemo中显示无网络](http://opn79542e.bkt.clouddn.com/6C3000A56F0B6A30818EF85D257A0E5E.jpg)

**Comment by yanzhenjie** [comment]
尝试修复了网络检测模块。

**Comment by yanzhenjie** [comment]
目前最新版本是1.1.5，如果还有问题的话重新开个issue讨论吧。
