### ISSUE TITLE
能否封装一个下载管理器的功能

### ISSUE THREAD

**Issue by Harvey-Lin** [yanzhenjie/NoHttp#14]

**Comment by yanzhenjie** [comment]
@Harvey-Lin 本周末打算做一个下载管理器的直播，到时候来看直播噢

**Comment by jksfood** [comment]
期待

**Comment by Struggle2016** [comment]
@yanzhenjie 请问直播的地址能否在发一份呢？你之前在百度云的链接失效了！谢谢

**Comment by tianshaokai** [comment]
@yanzhenjie  作者是否考虑加一个 下载管理的功能呢，我现在正在做这功能，感觉有点麻烦，我一个页面两个下载 列表，还有一个下载管理页面，都要同时更新进度，作者有什么思路吗

**Comment by shibenli** [comment]
@tianshaokai ，你这种需求看看[EventBus](https://github.com/greenrobot/EventBus)能不能满足你的需求，一个基于事件订阅的库。
