### ISSUE TITLE
NoHttp可以在一个请求中同时提交JSON和InputStream吗？

### ISSUE THREAD

**Issue by hupu123** [yanzhenjie/NoHttp#146]
因为一个接口中不仅要上传文件，还要传入一些参数
`request.setDefineRequestBodyForJson(JsonString);`
`request.setDefineRequestBody(InputStream, ContentType);`
这两句同时用会不会报错？

**Comment by yanzhenjie** [comment]
Http中`body`是唯一的，不能同时设置两种不同类型的`body`。你的需要可以参考[ReadMe#添加参数](https://github.com/yanzhenjie/NoHttp#添加参数)。

**Comment by hupu123** [comment]
好的，十分感谢！ @yanzhenjie
