### ISSUE TITLE
Out of memory 

### ISSUE THREAD

**Issue by lpengpeng** [yanzhenjie/NoHttp#149]
这个就是重复不停点击一个页面，然后就会报这个错误，查了下是new 的线程
太多了，超过极限了，但是我用的这个框架啊，这个不是队列吗？怎么还会报这个
libc: pthread_create failed: clone failed: Out of memory  
Throwing OutOfMemoryError "pthread_create (1040KB stack) failed: Out of memory"

**Comment by yanzhenjie** [comment]
贴代码，截图。
