### ISSUE TITLE
哪位大神可以讲一下RecyerlViewAdapter怎么写的吗

### ISSUE THREAD

**Issue by kongminggg** [yanzhenjie/NoHttp#15]
菜鸟一个，sample里面的那个RecyerlViewAdapter的封装看不明白，可以给稍微讲一讲吗，谢谢

**Comment by yanzhenjie** [comment]
嘿嘿，这个都不属于NoHttp的范围了。不过你可以在ReadMe上加群，去群里讨论吧。
