### ISSUE TITLE
关于Java URLEncoder.encode对空格导致的bug

### ISSUE THREAD

**Issue by Ordosbxy** [yanzhenjie/NoHttp#156]
我公司产品采用了Nohttp作为网络请求框架，其中涉及到好多Post提交。
例如，提交日期和时间“2018.01.01 15:49:00”,  NoHttp会对所有参数进行URLEncode.encode操作, Java的encode会将空格加密成+号，decode完的结果就成了“2018.01.01+15:49:00”。
　   网上说是最好使用Android的Uri.encode。 附两篇关于URLEncode.encode导致的文章。望博主回复一下这种情况怎么解决比较好，谢谢！
       [URI encode与URL encode对空格的不同处理](http://blog.csdn.net/caowenbin/article/details/8461598)
       [Android URL encode 空格处理](http://blog.csdn.net/top_code/article/details/26288057)
       
       急！

**Comment by Ordosbxy** [comment]
![encode](https://user-images.githubusercontent.com/2084298/34512785-6d21e9a4-f09f-11e7-8c3f-61bb4eba7151.png)
这是看NoHttp源码看到的对所有提价的参数进行了 URLEncode.encode 。谁有好的解决方案请个人大神回复一下，谢谢！

**Comment by yanzhenjie** [comment]
测试代码：
```java
System.out.println("----测试非全空格字符串----");
String notAllSpace = URLEncoder.encode("我是 测试 字符串", "utf-8");
System.out.println("notAllSpace URLEncoder: " + notAllSpace);
System.out.println("notAllSpace URLDecoder: " + URLDecoder.decode(notAllSpace, "utf-8"));

System.out.println("----测试全空格字符串----");
String allSpace = URLEncoder.encode("    ", "utf-8");
System.out.println("allSpace URLEncoder: " + allSpace);
System.out.println("allSpace URLDecoder: " + URLDecoder.decode(allSpace, "utf-8"));

System.out.println("----测试加号----");
String plusString = URLEncoder.encode("++", "utf-8");
System.out.println("nullString URLEncoder: " + plusString);
System.out.println("nullString URLDecoder: " + URLDecoder.decode(plusString, "utf-8"));

System.out.println("----测试空字符串----");
String nullString = URLEncoder.encode("", "utf-8");
System.out.println("nullString URLEncoder: " + nullString);
System.out.println("nullString URLDecoder: " + URLDecoder.decode(nullString, "utf-8"));
```

测试结果：
```
----测试非全空格字符串----
notAllSpace URLEncoder: %E6%88%91%E6%98%AF+%E6%B5%8B%E8%AF%95+%E5%AD%97%E7%AC%A6%E4%B8%B2
notAllSpace URLDecoder: 我是 测试 字符串
----测试全空格字符串----
allSpace URLEncoder: ++++
allSpace URLDecoder:     
----测试加号----
nullString URLEncoder: %2B%2B
nullString URLDecoder: ++
----测试空字符串----
nullString URLEncoder: 
nullString URLDecoder: 
```

很多情况下都不需要服务端去Decode，因为服务器会自动Decode。一般是服务器的Web框架或者服务器软件自动处理的。

你们服务端是什么语言的，我们服务端使用Java和PHP没有出现你说的这个问题。

**Comment by hhsj168** [comment]
用android.util下的Base64转码
Base64.encodeToString(rawHmac, Base64.NO_WRAP)
![image](https://user-images.githubusercontent.com/14695765/36651889-2333ad0c-1ae6-11e8-8d7b-ba602e6ed64c.png)
