### ISSUE TITLE
java.lang.NullPointerException

### ISSUE THREAD

**Issue by zhouhoude** [yanzhenjie/NoHttp#157]
Attempt to invoke virtual method 'void com.yanzhenjie.nohttp.rest.Messenger.start()' on a null object reference  com.yanzhenjie.nohttp.rest.RequestDispatcher.run(RequestDispatcher.java:81)

Attempt to invoke virtual method 'void com.yanzhenjie.nohttp.rest.Messenger.response(com.yanzhenjie.nohttp.rest.Response)' on a null object reference com.yanzhenjie.nohttp.rest.RequestDispatcher.run(RequestDispatcher.java:91)

**Comment by yanzhenjie** [comment]
是哪个版本出现的？

**Comment by adzcsx2** [comment]
1.1.8 出现太频繁了

**Comment by HarveyLee1228** [comment]
并没有解决啊，1.1.10还是有同样的问题
