### ISSUE TITLE
TV 有线网络连接时无法联网

### ISSUE THREAD

**Issue by harv** [yanzhenjie/NoHttp#158]
https://github.com/yanzhenjie/NoHttp/blob/321ab16c28e3eca40d1055da1cafca3aedce0ccf/nohttp/src/main/java/com/yanzhenjie/nohttp/HttpConnection.java#L71

https://github.com/yanzhenjie/NoHttp/blob/321ab16c28e3eca40d1055da1cafca3aedce0ccf/nohttp/src/main/java/com/yanzhenjie/nohttp/tools/NetUtils.java#L95

commit https://github.com/yanzhenjie/NoHttp/commit/2fe9e76abbd4ca96700272b7bb5e83f4033a8438 将 **isNetworkAvailable** 改成了只判断 **wifi 和手机网络**

**Comment by imknown** [comment]
蓝牙等也是可以连接互联网的.
