### ISSUE TITLE
接口请求总是报错怎么排查

### ISSUE THREAD

**Issue by douya40** [yanzhenjie/NoHttp#159]
Request<JSONObject> request = new FastJsonRequest(Constants.API.HUB_URL_newsp+"/"+MyPreferencesStorageModule.getInstance().getString("id","")+"/equipments", RequestMethod.PUT);
         String dystr=JSON.toJSONString(mylist);
        request.setDefineRequestBodyForJson(dystr);
        request(DYLK, request, jsonHttpListener, false, true);

onFailed(int what, Response<JSONObject> response)报下面错误
com.alibaba.fastjson.JSONArray cannot be cast to com.alibaba.fastjson.JSONObject

**Comment by yanzhenjie** [comment]
接口返回的数据是JsonArray，你转成JsonObject当然不行了。  
封装参考这篇文章：[http://blog.csdn.net/yanzhenjie1003/article/details/70158030](http://blog.csdn.net/yanzhenjie1003/article/details/70158030)
