### ISSUE TITLE
上传速度很慢怎么破？

### ISSUE THREAD

**Issue by dun1993** [yanzhenjie/NoHttp#16]
没办法吗?大文件上传都这样吗，试了很多种方法，都慢

**Comment by yanzhenjie** [comment]
这个和网络带宽有关的，大文件肯定慢了，你可以监听下上传进度，setUploadListener

**Comment by dun1993** [comment]
嗯嗯，谢谢！

2016-07-02 17:49 GMT+08:00 严振杰 <notifications@github.com>:
