### ISSUE TITLE
大神 有在NoHttp外部直接用url就能拿到该url缓存的方法吗

### ISSUE THREAD

**Issue by xzhixian** [yanzhenjie/NoHttp#2]
求大神暴露个拿缓存的方法，在网络不好的情况下能先拿到缓存去用。

**Comment by Y0LANDA** [comment]
可以拿到的，不过NoHttp目前只支持标准的http 304缓存。详细的情况你可以加ReadMe中的QQ群1，我们可以当面详细的解释，因为目前文档方面正在完善，请多多包涵喔！

**Comment by Y0LANDA** [comment]
缓存的接口已开放，这位朋友用的还可以吧？
