### ISSUE TITLE
如何用一个进度条显示下载队列的进度？

### ISSUE THREAD

**Issue by gjjofsfe** [yanzhenjie/NoHttp#21]
页面上只有一个下载进度条，如果有多个文件需要下载，如何控制下载总进度的显示？
另外，没找到断点下载的代码，sample里面的使用，是否支持了断点下载？

**Comment by yanzhenjie** [comment]
@gjjofsfe 有多文件一起下载的demo，认真看下demo。

**Comment by gjjofsfe** [comment]
我的意思是说，如果需要下载多个文件，而且页面上只有一个总的下载进度，DownloadListener那里可以再封装一下。

**Comment by yanzhenjie** [comment]
@gjjofsfe 多个文件的onProgress回调后，把进度叠加，除以任务总数就多多个文件的总进度。
