### ISSUE TITLE
get请求下载的时候出现下载的Zip包不完整？？？

### ISSUE THREAD

**Issue by leoncoding** [yanzhenjie/NoHttp#25]
get请求下载的时候出现下载的Zip包不完整

**Comment by yanzhenjie** [comment]
非常感谢你支持我的框架。
我看到你给我发的邮件了，也回了你邮件，为了免得其它人遇到一样的问题。
如果之前是post可以，你很着急的就换用post请求先。
get下载一般不要提交json类型的参数，需要push一段json到服务器，一般都是json，那么也要求服务器支持这种操作。get一般都是请求一个静态的url，最多后面用?uname=yolanda&upwd=12345这种形式。下载不完整这种情况你可以在创建请求的时候禁用断点续传、删除老文件：NoHttp.createDownloadRequest(url, method, folder, false, true)。你这样试试，如果不行继续沟通。
