### ISSUE TITLE
该库是否考虑支持rxjava，请求网络完成后可以返回一个Observable

### ISSUE THREAD

**Issue by tianshaokai** [yanzhenjie/NoHttp#26]

**Comment by Harlber** [comment]
该功能实现起来后就要和rx挂钩了，如果作者允许的话，我过段时间提个PR

**Comment by tianshaokai** [comment]
@Harlber  你已经写好了？？

**Comment by Harlber** [comment]
没有，这几天刚好在看Retrofit~感觉可以实现

**Comment by tianshaokai** [comment]
@Harlber  希望可以支持rxjava，那样就方便多了哈哈

**Comment by tianshaokai** [comment]
不过作者的意图好像是不想依赖任何第三方类库，只想单独做一个网络框架

**Comment by Harlber** [comment]
不能这么说呀，本身这个库比较小，如果纯粹为了使用rx而引入庞大的rx，感觉得不偿失

**Comment by yanzhenjie** [comment]
目前暂时不打算支持，你可以fork一个分支过去，可以叫做RxNoHttp，说不定比我原生的更好用喔。就像RxAndroid一样，依赖RxJava。
同时，对于任何框架觉得合适自己，必要的就去用，上面那哥们说的挺对的。如果有人对NoHttp好好的想法的话，欢迎PR，大家一起来完善。

**Comment by tianshaokai** [comment]
@Harlber 嗯rxjava 库是挺大的
