### ISSUE TITLE
在教程中首先注明要先初始化

### ISSUE THREAD

**Issue by zhongzilu** [yanzhenjie/NoHttp#27]
我首次使用该框架，按照网上的教程写了个简单的发送get的请求，在运行时报错才知道需要先在Application中先初始化，然而几乎在所有的教程中都没有写明这个一点，希望作者能加上，免得下次新手在使用的过程中才发现需要先初始化

**Comment by yanzhenjie** [comment]
demo和博客中都有说明，可能在ReadMe中没有说明，下个版本发布时会加上，谢谢。
