### ISSUE TITLE
多個文件上傳問題?

### ISSUE THREAD

**Issue by a3858293** [yanzhenjie/NoHttp#28]
開發者大大您好，我想上傳多個檔案，以下是我的部分代碼 

File file1 = new File(Environment.getExternalStorageDirectory().getPath()+"/xxx.txt");
File file2 = new File(Environment.getExternalStorageDirectory().getPath()+"/yyy.txt");

BasicBinary binary1 = new FileBinary(file1);
BasicBinary binary2 = new FileBinary(file2);

request.add("file", binary1);
request.add("file", binary2);

requestQueue.add(NOHTTP_WHAT_TEST, request, onResponseListener);

php端接收：

<?php  
    //获取文件类型  
    $type = $_FILES["file"]["type"];  
    //获取文件大小  
    $size = $_FILES["file"]["size"];    
    
        //判断文件大小是否超出30KB  
        if($size > 600 * 1024){  
            echo "file size invalid, size > 600kb";  
        }else{  
            //如果出错就输出错误信息  
            if($_FILES["file"]["error"] > 0){  
                echo "upload file error !";  
            }else{  
                //没有错误，就拷贝上传的文件到指定的目录  
                $name = $_FILES["file"]["name"];  
                $dir = "upload/";  
                //如果目录不存在，就创建  
                if(!file_exists($dir)){  
                    mkdir("upload/");  
                }  
                //判断文件是否已存在  
                if(file_exists("upload/" . $name)){  
                    echo "file exist";  
                }else{  
                    //指定目录下不存在文件，则拷贝文件  
                    move_uploaded_file($_FILES["file"]["tmp_name"], "upload/" . $_FILES["file"]["name"]);  
                    echo "upload file complete";  
                }  
            }  
        }  
 
?> 

上傳之後只會有 yyy.txt ，xxx.txt好像不會被上傳，是哪邊代碼有少打嗎?

還請大神賜教。

**Comment by yanzhenjie** [comment]
首先要確定下你的NoHttp的版本，在NoHttp1.0.4之前多文件上傳，每個文件只能有一個獨立的key，否則會被覆蓋，我猜你的情況可能是`request.add("file", XXXBinary)`被request.add("file", YYYBinary)覆蓋了。
其次NoHttp1.0.4開始支持一個Key上傳一個FileList，這樣的話支持這樣寫：
```java
request.add("file", XXXBinary);
request.add("file", YYYBinary);
```
或者
```java
List<Binary> binaries = new ArrayList<>();
binaries.add(XXXBinary);
binaries.add(YYYBinary);
binaries.add(ZZZBinary);
request.add("file", binaries);
```
最後，如果你使用的NoHttp版本是1.0.4或者更高，那麼可能是你PHP服務器的文件被覆蓋了。
歡迎繼續留言。

**Comment by a3858293** [comment]
開發者大大您好，我使用的版本是 1.0.4 ，因為我 php 代碼也是參考其他大大寫的，如果要讓php代碼不被覆蓋，需要設定什麼參數嗎?

**Comment by a3858293** [comment]
File file1 = new File(Environment.getExternalStorageDirectory().getPath()+"/xxx.txt");
File file2 = new File(Environment.getExternalStorageDirectory().getPath()+"/yyy.txt");

開發者大大您好，我上傳的檔名是不一樣的，這樣我php也會被覆蓋過去嗎?

**Comment by yanzhenjie** [comment]
你看看我上面回答的，我剛才完善過了。如果你成功解決了，請在這裡回覆一下。服務端的php要保證不能覆蓋文件，這個你可以搜索一下其他人寫的。
