### ISSUE TITLE
您好，怎么解决中文乱码的问题

### ISSUE THREAD

**Issue by kxzhe** [yanzhenjie/NoHttp#31]
您好，目标网页是gbk编码的，用get方法获取网页内容，在succeed里取出中文的时候乱码，请问怎么解决呢？

        public void onSucceed(int what, Response<String> response) {
            String result =  response.get()
            TextView tvRet = (TextView) findViewById(R.id.tvRet);
            tvRet.setText(result);
        }

**Comment by yanzhenjie** [comment]
在http相应头中，有一个ContentType字段，这个字段决定了内容的编码格式，html内容可能和这里指定的格式不一样，所以导致了乱码。两种方式：
1. 自定义请求，重写onResponse方法，自己byte[]数据为String，根据你们自己的编码格式。
2. 就这onSucceed中response.byteArray();拿到byte[]自己解析成String。
3. 让你们网站的人员统一http相应头中ContentType和html真正的编码格式。
