### ISSUE TITLE
RequestMethod.class的问题

### ISSUE THREAD

**Issue by yandeqing** [yanzhenjie/NoHttp#32]
public boolean allowRequestBody() {
        boolean allowRequestBody = this == POST || this == PUT || this == PATCH || this == DELETE;
        if (Build.VERSION.SDK_INT < AndroidVersion.LOLLIPOP)
            allowRequestBody = allowRequestBody && this != DELETE;
        return allowRequestBody;
    }
目前在安卓6.0上delete方法服务器端拿不到参数,最终追到这里,不知道版主这个方法为什么这样写

**Comment by yanzhenjie** [comment]
因为6.0以上，delete的方式和post一样，是用body发送的。
