### ISSUE TITLE
咨询关于httplistener

### ISSUE THREAD

**Issue by enjoydiy** [yanzhenjie/NoHttp#33]
在daemon中看到实现了一个接口HttpListener<T>,  但是在nohttp源码中看到有OnResponseListener<T>, 为什么不直接用OnResponseListener<T>? 这样有什么好处吗?

**Comment by yanzhenjie** [comment]
NoHttp默认的是OnResponseListener，HttpListener是demo自定义的一个回调，因为Demo对NoHttp做了业务逻辑的封装，把OnResponseListener封装好了，再用HttpListener来回调给调用者。
