### ISSUE TITLE
微信支付请求失败，hostname 解析失败

### ISSUE THREAD

**Issue by zongren** [yanzhenjie/NoHttp#34]
![weixin](https://cloud.githubusercontent.com/assets/4525819/17611373/3d70bf1c-6079-11e6-96bd-052bf8b43200.png)

**Comment by yanzhenjie** [comment]
<image src="http://img.blog.csdn.net/20160812105719380" />
你看下我这里请求你这个地址的时候是可以的，你不是地址填了空格之类的呢？再试试。

**Comment by zongren** [comment]
链接本身应该是对的
<img width="854" alt="qq20160812-1 2x" src="https://cloud.githubusercontent.com/assets/4525819/17611714/3ca70dcc-607c-11e6-9a67-37773fc5170f.png">
这是我的调用方法
<img width="750" alt="qq20160812-2 2x" src="https://cloud.githubusercontent.com/assets/4525819/17611728/5964387c-607c-11e6-84a4-c845768f466c.png">

**Comment by zongren** [comment]
没问题了，应该是我的Android模拟器有问题
