### ISSUE TITLE
nohttp是基于soket通讯的吗？可以用于soket请求吗？可以传报文格式吗？

### ISSUE THREAD

**Issue by XaXoYi369** [yanzhenjie/NoHttp#35]
你好，请问下nohttp是基于soket通讯的吗？可以用于soket请求吗？可以传报文格式吗？

**Comment by yanzhenjie** [comment]
基于HttpURLConnection的，支持基于http协议的通信。可以传报文。

**Comment by XaXoYi369** [comment]
我还想问下，现在这边后台是基于soket通讯的，不知道可不可以用这个框架？

**Comment by yanzhenjie** [comment]
Http本身就是基于Socket的，但是实现的是Http协议，后端如果提供的是Http接口就可以用NoHttp。如果单纯的是Socket的话，客户端也要用Socket来做。

**Comment by XaXoYi369** [comment]
你好，我想请问下https请求，客户端只有加密证书，没有公钥，通过证书获取公钥？谢谢！
