### ISSUE TITLE
有提问

### ISSUE THREAD

**Issue by Honsec** [yanzhenjie/NoHttp#38]
> 添加到队列
> 
> RequestQueue requestQueue = NoHttp.newRequestQueue();
> // 或者传一个并发值，允许三个请求同时并发
> // RequestQueue requestQueue = NoHttp.newRequestQueue(3);
> 
> // 发起请求
> requestQueue.add(what, request, responseListener);
> 　　上面添加到队列时有一个what，这个what会在responseLisetener响应时回调给开发者，所以我们可以用一个responseLisetener接受多个请求的响应，用what来区分结果。而不用像有的框架一样，每一个请求都要new一个回调。

这个`而不用像有的框架一样，每一个请求都要new一个回调。`    我觉得还是每次请求都new 一个比较好。
这样不得把很多request 结果处理写到一个listener里头啊

**Comment by yanzhenjie** [comment]
并不是，这样是你多了选择，你可以多个请求用一个Listener，也可以每个请求重新new。就像handler的waht一样。
