### ISSUE TITLE
requestQueue.add(what, request, responseListener); 第一个参数只能是int型吗？

### ISSUE THREAD

**Issue by kazeik** [yanzhenjie/NoHttp#41]
个人偏好用String来标识当前是哪一个接口的请求，有时候选择用接口名来标识当前是哪一个接口的请求，但目前粗略的看到你这里只是一个int型。粗略的考虑了，int型在区别哪一个接口时，还得特意为它定义变量才行。。
是否，有用String作为标识的重载方法？

**Comment by yanzhenjie** [comment]
关于这一点你可能认识的不太够。
1. 你用过其他框架就知道，根本没有这种标志，也就是只有第二个和第三个参数。
2. 做标志最好的是int类型，其他类型更占内存。
3. 这个what就相当于是handler的那个what一样的用法。
4. String类型不也是一样需要特意定义变量吗？

综上所述，int是最好的，如果你非要使用String也是可以的，你可以用我的同步请求重新结合RxJava封装一次，NoHttp的异步请求就是利用同步请求加Handler又封装的。
