### ISSUE TITLE
文件下载出现问题

### ISSUE THREAD

**Issue by huangjim** [yanzhenjie/NoHttp#43]
你好，我在你的demo的单个文件下载界面修改了一下，我要多个url顺序下载，我先把这些url创建DownloadRequest并保存到list里面，然后一个下载完成后就进行下一个下载，但是当我点击暂停时，就不能恢复下载了，我debug发现好像在点cancel的时候，blockquene没有把这个移除掉。希望帮忙确认一下是什么问题，谢谢。

**Comment by yanzhenjie** [comment]
正在确认，稍等下。

**Comment by huangjim** [comment]
其实我不是并发，是单个按顺序下载，所有创建实例是和demo一样的，点了暂停在点开始时有l一个log提示是....url....is canceled，后面都没反应了，重新进入再开始是可以继续下载的，Downloadquene里面的mUnFinishQueue是什么时候加入数据的

**Comment by yanzhenjie** [comment]
我明白你不需要并发，不知道你的额一个个下载如果没有用队列是怎么做到的。
点击了暂停是调用request.cancel()，这个下载被取消了，你下载继续时应该重新new一个request出来加入队列，你可以在demo的单个文件下载中找到相关逻辑。

**Comment by huangjim** [comment]
非常感谢你的及时回复，我就是在单个文件的逻辑上修改的，而且同样的写法在1.0.0的demo里面是没问题的，我迁移到1.0.6才出现这样的问题，实在抱歉打扰了。

**Comment by yanzhenjie** [comment]
那你下载1.0.6的demo看下，这个1.0.0和1.0.6的变化几乎可以忽略的，应该不会影响到，发布的时候我已经测试过了，1.0.5和1.0.6代码是没有变化的，就是整理了下，然后又发布了一个基于okhttp的版本：https://github.com/yanzhenjie/NoHttp4OkHttp

**Comment by huangjim** [comment]
我发现这个问题是出在，当我把根据url把DownloadRequest生成为全局变量，就是提前创建好的时候，在恢复下载的时候调用  CallServer.getDownloadInstance().add(0, mDownloadRequest, downloadListener);就无法恢复了，而mDownloadRequest重新根据同样的参数创建就可以重新下载，这是为什么呢

**Comment by huangjim** [comment]
就在最新的demo里面的单个文件下载就可以试试

**Comment by yanzhenjie** [comment]
上面已经回复过这个问题了。
![需要重新new](https://cloud.githubusercontent.com/assets/13534988/18377088/364a91fc-7697-11e6-88d5-4555cf76c60b.png)

**Comment by huangjim** [comment]
这个问题在1.0.0的不用重新创建的

**Comment by yanzhenjie** [comment]
嗯1.0.0当时重新添加时动态修改了取消状态的，但是这么做对于框架是不合理的，所以就取消了。
如果你用了之后的版本的话需要重新创建，建议使用新版，1.0.0这个版本后期升级修改了api的。

**Comment by huangjim** [comment]
好的，谢谢。
