### ISSUE TITLE
问问有关架构的东西

### ISSUE THREAD

**Issue by LcxAndroidwawa** [yanzhenjie/NoHttp#46]
达哥 最近看了nohttp的源码 我怎么感觉你的架构 和Volley的架构很相似 是不是你在开发的时候 参考了Volley的东西

**Comment by yanzhenjie** [comment]
你应该是只看了队列吧，队列都这样的，就像写页面大家都是继承Activity开始的。
那只是NoHttp的1/10的一小部分，NoHttp的同步访问才是NoHttp的核心，队列只是在NoHttp的同步基础上封装了Handler等。

你提出这个问题，你应该是才开始看，如果后续有问题欢迎继续交流哈。

**Comment by yanzhenjie** [comment]
架构是完全不同的，你应该是只看了队列吧，队列都这样的，就像写页面大家都是继承Activity开始的。
那只是NoHttp的1/10的一小部分，NoHttp的同步访问才是NoHttp的核心，队列只是在NoHttp的同步基础上封装了Handler等。

你提出这个问题，你应该是才开始看，如果后续有问题欢迎继续交流哈。
