### ISSUE TITLE
几个小问题

### ISSUE THREAD

**Issue by DysaniazzZ** [yanzhenjie/NoHttp#48]
* 我看您在给出的 demo 里把 `RequestQueue` 的获取弄成单例了，但是这样是不是并发请求数就固定了，如果有特殊需要，还要自己再获取另一个可以指定并发请求数的 `RequestQueue` 呢？
* 还有就是在首页 `StartActivity` 退出时执行了三步操作：先取消所有请求，然后停止所有请求队列，最后杀死进程，请问这样是必要的也必须按照这个顺序来吗？

**Comment by yanzhenjie** [comment]
1. 是的，正式开发中可以做多个单例来适应不同的场景。
2. 首页退出是因为app退出了，所以取消了所有请求、停止了队列，这不是必须的。
 - 如果队列中有请求，退出时肯定要取消的，停止队列就会杀死所有子线程，下一次必须重新生成单例，否则这个单例再被调用请求将不被执行。

**Comment by DysaniazzZ** [comment]
哦哦，谢谢大神的讲解。也就是说在 App 退出时保证清除队列和释放资源就可以了吧。刚开始用这个框架，感觉还是挺好用的，后续如果遇到问题还希望大神多多指教。:)

**Comment by yanzhenjie** [comment]
感谢支持，有问题随时来。
