### ISSUE TITLE
关于NoHttp有两个问题！请指教

### ISSUE THREAD

**Issue by Struggle2016** [yanzhenjie/NoHttp#50]
1.如何用NoHttp实现多图片上传？2.如何设置框架的请求超时时间？

**Comment by yanzhenjie** [comment]
更多详情看下README。
1. 只需要多次添加binary即可：
'Request.add(String, Binary)'
或者
'request.add(String, List<Binary>)'。
2. 全局配置
连接超时'NoHttp.setConnectionTimeout'
服务器响应超时'NoHttp.setReadTimeout'

单个Request配置
连接超时'Request.setConnectionTimeout'
服务器响应超时'Request.setReadTimeout'

感谢支持。

**Comment by shibenli** [comment]
回复还是很及时的，不过看现在的issue都是关于使用方面的，希望有更多的人参与进来

**Comment by yanzhenjie** [comment]
@shibenli @Struggle2016 现在正在完善NoHttp的文档，文档地址是：[http://doc.nohttp.net/](http://doc.nohttp.net/)，有问题可以阅读文档，如果文档没讲清楚的，可以给我反馈，我会及时更新的。

**Comment by shibenli** [comment]
@yanzhenjie，感觉文档的话放在github上的那个就可以了吧，你这是自己整的？
