### ISSUE TITLE
请教一个问题

### ISSUE THREAD

**Issue by douya40** [yanzhenjie/NoHttp#51]
使用nohttp,如何将网络请求单独写在一个类里面，然后回调到对应的activity或fragment里面

**Comment by douya40** [comment]
怎么具体的实现呢

**Comment by yanzhenjie** [comment]
看下Demo的CallServer类，就是把NoHttp单独封装到一个类中了，应该能满足你的要求，如果还不够的话，你可以把Request在这个类中new，然后你在外面调用的时候值需要传Map进来。

**Comment by douya40** [comment]
能在新版本上面写个demo吗？我改的没有你改的好

**Comment by yanzhenjie** [comment]
你又没有加ReadMe中讲的开发群，群里面有很多人已经封装号了，还是结合RxJava的，封装的比我的好多了，你可以参考一下。
