### ISSUE TITLE
支持缓存自定义key吗？

### ISSUE THREAD

**Issue by wqandroid** [yanzhenjie/NoHttp#52]
因为在客户端请求的时候 经常会有参数是动态的！okhttp默认是url+参数 md5生产的key！造成带动态参数的缓存就没有意义了！

**Comment by yanzhenjie** [comment]
设置缓存模式：`request.setCacheMode(CacheMode.xxx);`
设置缓存的Key：`request.SsetCacheKey("xxx");`

**Comment by wqandroid** [comment]
好的谢谢了 ！非常不错
