### ISSUE TITLE
response.isSucceed()这个方法的逻辑有问题

### ISSUE THREAD

**Issue by mundane799699** [yanzhenjie/NoHttp#53]
response.isSucceed()这个方法好像并不能用来判断请求是否成功啊.   我试了, 明明状态已经是404了, response.isSucceed()返回的却是true, 我觉得应该根据code是否在200到300之间来判断是否是success

**Comment by yanzhenjie** [comment]
请看这个方法的JavaDoc，这个方法的意思是Http层面的请求成功，表示请求途中没有发生任何问题，和服务器通信成功。http的状态码有很多，200段、300段、400段、500段都可能是成功，服务器可以自定义这些状态码的，所有你所说的成功是你们业务的成功，所有需要你自己根据你们服务器约定的成功状态码来判断是否真正的成功，比如我们服务器约定的响应码是200才是成功，我是这样做的：```if(response.responseCode == 200) {...}`

**Comment by mundane799699** [comment]
行, 那我以后就用responseCode来判断了
