### ISSUE TITLE
如何设置缓存失效时间？

### ISSUE THREAD

**Issue by zdd** [yanzhenjie/NoHttp#55]
如题。

**Comment by yanzhenjie** [comment]
本地不管理缓存失效时间，NoHttp有5中缓存模式，其中默认是Default模式，这种模式遵守Http标准协议。
比如http 304重定向缓存，eTag、expire、LastModifyTime这些都支持的，这种模式是带有过期时间的，并且服务器可以动态设置过期时间，具体是客户端请求服务器的时候，服务器在http相应头添加相应的控制头，可以告诉服务端的同学去做一下。
