### ISSUE TITLE
为什么要使用1.8

### ISSUE THREAD

**Issue by TonyJason** [yanzhenjie/NoHttp#56]
挺好的一个项目，但是不懂1.8的那个什么表达式，电脑也没安装1.8  请问有1.7版本的吗

**Comment by yanzhenjie** [comment]
只是demo用了lambda而已，原项目是是支持1.6  1.7的，可以放心使用。
demo如果运行遇到问题的话，有三种方案：  
1. 装1.8的jdk。  
2. 看详细文档的教程：[doc.nohttp.net](http://doc.nohttp.net)  
3. 把原来的lambda转换为普通代码，方法：复制原来把lambda中的方法体，然后删除lambda表达式，在原来的lambda处new一个接口（as自动提示）出来，把复制的方法体粘贴进去即可。
