### ISSUE TITLE
NoHttp 如何上传大文件（30M左右zip文件）？用Simple中的例子会抛异常出来

### ISSUE THREAD

**Issue by bdliang** [yanzhenjie/NoHttp#59]
11-08 16:04:34.221: E/NoHttpSample(26087): java.net.SocketException: sendto failed: EPIPE (Broken pipe)
11-08 16:04:34.221: E/NoHttpSample(26087): 	at libcore.io.IoBridge.maybeThrowAfterSendto(IoBridge.java:546)
11-08 16:04:34.221: E/NoHttpSample(26087): 	at libcore.io.IoBridge.sendto(IoBridge.java:515)
11-08 16:04:34.221: E/NoHttpSample(26087): 	at java.net.PlainSocketImpl.write(PlainSocketImpl.java:504)
11-08 16:04:34.221: E/NoHttpSample(26087): 	at java.net.PlainSocketImpl.access$100(PlainSocketImpl.java:37)
11-08 16:04:34.221: E/NoHttpSample(26087): 	at java.net.PlainSocketImpl$PlainSocketOutputStream.write(PlainSocketImpl.java:266)
11-08 16:04:34.221: E/NoHttpSample(26087): 	at com.android.okio.Okio$1.write(Okio.java:73)
11-08 16:04:34.221: E/NoHttpSample(26087): 	at com.android.okio.RealBufferedSink.flush(RealBufferedSink.java:154)
11-08 16:04:34.221: E/NoHttpSample(26087): 	at com.android.okhttp.internal.http.HttpConnection.flush(HttpConnection.java:130)
11-08 16:04:34.221: E/NoHttpSample(26087): 	at com.android.okhttp.internal.http.HttpTransport.flushRequest(HttpTransport.java:80)
11-08 16:04:34.221: E/NoHttpSample(26087): 	at com.android.okhttp.internal.http.HttpEngine.readResponse(HttpEngine.java:794)
11-08 16:04:34.221: E/NoHttpSample(26087): 	at com.android.okhttp.internal.http.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:405)
11-08 16:04:34.221: E/NoHttpSample(26087): 	at com.android.okhttp.internal.http.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:349)
11-08 16:04:34.221: E/NoHttpSample(26087): 	at com.android.okhttp.internal.http.HttpURLConnectionImpl.getResponseCode(HttpURLConnectionImpl.java:517)
11-08 16:04:34.221: E/NoHttpSample(26087): 	at com.yolanda.nohttp.BasicConnection.getConnection(BasicConnection.java:88)
11-08 16:04:34.221: E/NoHttpSample(26087): 	at com.yolanda.nohttp.rest.HttpRestConnection.sendRequestHandleRetry(HttpRestConnection.java:135)
11-08 16:04:34.221: E/NoHttpSample(26087): 	at com.yolanda.nohttp.rest.HttpRestConnection.requestNetwork(HttpRestConnection.java:92)
11-08 16:04:34.221: E/NoHttpSample(26087): 	at com.yolanda.nohttp.rest.HttpRestParser.parserRequest(HttpRestParser.java:52)
11-08 16:04:34.221: E/NoHttpSample(26087): 	at com.yolanda.nohttp.rest.RequestDispatcher.run(RequestDispatcher.java:101)
11-08 16:04:34.221: E/NoHttpSample(26087): Caused by: android.system.ErrnoException: sendto failed: EPIPE (Broken pipe)
11-08 16:04:34.221: E/NoHttpSample(26087): 	at libcore.io.Posix.sendtoBytes(Native Method)
11-08 16:04:34.221: E/NoHttpSample(26087): 	at libcore.io.Posix.sendto(Posix.java:176)
11-08 16:04:34.221: E/NoHttpSample(26087): 	at libcore.io.BlockGuardOs.sendto(BlockGuardOs.java:278)
11-08 16:04:34.221: E/NoHttpSample(26087): 	at libcore.io.IoBridge.sendto(IoBridge.java:513)
11-08 16:04:34.221: E/NoHttpSample(26087): 	... 16 more

**Comment by yanzhenjie** [comment]
NoHttp不限制文件上传大小。这个错误应该是你们服务器不允许上传过大的文件引起，具体咨询下你们服务器的人有没有限制客户端上传文件的大小。
