### ISSUE TITLE
get请求请求不到数据,post请求可以请求到数据

### ISSUE THREAD

**Issue by cdcdec** [yanzhenjie/NoHttp#61]
同一个接口在一个设备上(p89mini)get请求请求不到数据,post请求可以请求到数据,而这个接口在其它设备上get和post请求都能请求到数据。找了很久才找到这个问题，可不可以在响应里面对这种情况做一个提示？

**Comment by yanzhenjie** [comment]
你可以打开NoHttp的调试模式看看Log，NoHttp会把完整的请求过程和Log都打印出来的，这样子能很快定位是什么错。教程文档地址：[doc.nohttp.net](http://doc.nohttp.net)
