### ISSUE TITLE
现在框架里用的CookieManager是系统的CookieManger，所以Cookie会自动同步？

### ISSUE THREAD

**Issue by zongren** [yanzhenjie/NoHttp#64]
如题

**Comment by yanzhenjie** [comment]
你是说和WebView同步吗？是不一样的，不会同步，这个CookieManager只是个普通工具类，只是提供了某些方便操作数据的方法，WebView的CookieManager这个CookieManager不是一个东西。

**Comment by zongren** [comment]
能贴个如何同步两者的cookie的文章吗

**Comment by yanzhenjie** [comment]
NoHttp文档中详细介绍了：http://doc.nohttp.net/248698

**Comment by zongren** [comment]
thanks:smile:
