### ISSUE TITLE
NoHttp Post请求的时候，有无简单的设置数组请求参数

### ISSUE THREAD

**Issue by liuweijw** [yanzhenjie/NoHttp#65]
NoHttp Post请求的时候，有无简单的设置数组请求参数。
类似表单中多个input  相同name属性的值。暂时想到两种方式：
1、参数可以通过 url?name=1&name=2
2、将参数封装为JSON字符串对象传给服务端。

上面两中方式，需要动态组装，如果参数比较多的话，比较麻烦，框架中是否有这种类型参数的简单设置方式。

**Comment by yanzhenjie** [comment]
可以直接add：
