### ISSUE TITLE
重定向请求失败

### ISSUE THREAD

**Issue by zongren** [yanzhenjie/NoHttp#67]
我请求的链接发生两次302重定向
第二个重定向请求失败
第一个重定向Location返回完整的链接
第二个重定向Location返回部分链接
Requst使用的是StringRequest
截图如下所示
<img width="565" alt="qq20170106-2 2x" src="https://cloud.githubusercontent.com/assets/4525819/21708570/1c6225ee-d415-11e6-8ce9-5eaa22991c86.png">
<img width="537" alt="qq20170106-1 2x" src="https://cloud.githubusercontent.com/assets/4525819/21708574/21383874-d415-11e6-8558-900b6decc0e7.png">
<img width="741" alt="qq20170106-3 2x" src="https://cloud.githubusercontent.com/assets/4525819/21708591/566af16c-d415-11e6-8f7a-e0dfc77b4f39.png">

**Comment by yanzhenjie** [comment]
1. 重定向NoHttp默认取响应头的Location作为新的url访问。  
2.开发者可以使用request.setRedirectHandler()来监听，在监听中可以控制是否允许重定向，并且控制重定向的url等信息。

如果你的响应头的Location中有非完整url的话，那么你可以使用第二个方法。
