### ISSUE TITLE
nohttp请求失败

### ISSUE THREAD

**Issue by douya40** [yanzhenjie/NoHttp#68]
com.yolanda.nohttp.error.ServerError: Download fails, the server response code is 416: http://114.215.25.155:8080/laima/upload/shop/151/detail/shopIcon.jpg （这个原因是什么呢，nohttp里面都封装好的）

**Comment by yanzhenjie** [comment]
状态码问题请看这里：http://www.w3school.com.cn/tags/html_ref_httpmessages.asp
