### ISSUE TITLE
too many open file

### ISSUE THREAD

**Issue by qiulei19850103** [yanzhenjie/NoHttp#69]
同一个请求连续请求很多次，客户端就会报too many open file错误，导致客户端直接crash掉。

**Comment by yanzhenjie** [comment]
抱歉回复迟了，我们在测试的时候做过这样的测试，未发现你描述的情况。我相信你已经解决了问题，下次遇到类似问题时，在发起issue时你可以把异常信息、机型、系统版本都发一下。
