### ISSUE TITLE
NoHttp的请求在请求队列里面，可以设置优先级吗？

### ISSUE THREAD

**Issue by lmdiloveu** [yanzhenjie/NoHttp#7]
NoHttp的请求在请求队列里面，可以设置优先级吗？

**Comment by Y0LANDA** [comment]
优先级的设置NoHttp1.0.0暂时不支持，下一个版本支持，下一个版本就这几天发布。

**Comment by lmdiloveu** [comment]
明白，但是你有一篇博客有一个表，跟volley比较的，那里写着nohttp支持优先级设置的！文档是不是要改，说明版本

**Comment by yanzhenjie** [comment]
@lmdiloveu 可以设置优先级了，现在发布了NoHttp1.0.1。
