### ISSUE TITLE
com.yolanda.nohttp.error.ServerError: Download fails, the server response code is 416: http://192.168.1.250:1433/laima/upload/shop/127/detail/shopIcon.jpg

### ISSUE THREAD

**Issue by douya40** [yanzhenjie/NoHttp#71]
com.yolanda.nohttp.error.ServerError: Download fails, the server response code is 416: http://192.168.1.250:1433/laima/upload/shop/127/detail/shopIcon.jpg(这个问题问后台说是app问题。我用的是nohttp 下载一张图片服务器返回这个
)

**Comment by yanzhenjie** [comment]
是调用下载模块下载文件吗？你在new DownloadRequest时，传入的参数有一个isRange，填false禁用断点续传就可以了。
