### ISSUE TITLE
关于自动保存会话cookie的问题

### ISSUE THREAD

**Issue by zhangyan2013** [yanzhenjie/NoHttp#72]
nohttp每次请求完都保存cookie,然后有些请求是免会话认证的，此时nohttp保存cookie就是不正确的，然后再到需要cookie验证的请求就无法正常请求，请大师给予解决下！

**Comment by yanzhenjie** [comment]
1. 首先NoHttp是按照标准的Http协议来处理Cookie的。
2. 其它每个请求发起前都需要按照Http协议来添加Cookie，请求响应后也需要根据Http协议来保存或者更新Cookie。
3. 我认为NoHttp这样做是没有任何问题的，其次你说的解决需要怎样解决呢？

另外：你可以监听NoHttp对Cookie的操作，具体请看文档[doc.nohttp.net](http://doc.nohttp.net/)中**Cookie管理 WebView**同步章节。

如果你看了文档，这里提供一个办法：你可以对某个你不想保存的`Cookie#setMaxAge(0)`，让它的有效时间为0，Http协议中它就作废了，NoHttp以后也不会用这个Cookie了。

**Comment by zhangyan2013** [comment]
Cookie#setMaxAge(0)，让它的有效时间为0，Http协议中它就作废了!
如果这样，其它请求依然需要保持会话，让它有效时间为0，那么我后面的请求都无效了，这怎么办！

能不能在你那个监听里提供一个接口，默认是你这样自动保存，而且当返回false时不保存呢！

**Comment by yanzhenjie** [comment]
返回false不保存和`Cookie#setMaxAge(0)`有什么区别吗？

**Comment by yanzhenjie** [comment]
NoHttp一定是按照标准Http协议来做的，你可以在初始化的时候禁用Cookie的自动维护，你可以自己来维护Cookie，在每次响应的时候：`response.getHeader().getCookies()`可以拿到这次响应的所有Cookie。

**Comment by zhangyan2013** [comment]
嗯，我自己维护可以!
那请问，如果我自己维护cookie的话，我如何设置请求时的cookie?是request.setHeader("Cookie",*****)吗？

**Comment by yanzhenjie** [comment]
自己维护Cookie，必须要禁用NoHttp自动维护Cookie的功能。以下几种皆可：  
```java
...
String name = ...
String value = ...
request.addHeader("Cookie", name=value); // 或者setHeader("Cookie", name=value);
```

```java
...
HttpCookie cookie = ...
request.addHeader(cookie);
```

**Comment by zhangyan2013** [comment]
好的，谢谢！
