### ISSUE TITLE
NoHttp 在处理服务端请求时无法获取到服务端返回的错误信息内容

### ISSUE THREAD

**Issue by IrvingRyan** [yanzhenjie/NoHttp#8]
现在业务上要求除了获取返回码外，还需要对服务端错误内容进行分析，现在无法获取服务端错误信息内容。

**Comment by yanzhenjie** [comment]
@IrvingRyan 今天晚上最迟明天晚上修复这个问题，并发布一个版本出来，到时候及时更新下就OK了，多谢支持。

**Comment by yanzhenjie** [comment]
@IrvingRyan 这个问题在NoHttp1.0.1已经优化了，你现在可以看看咯。谢谢支持。

**Comment by IrvingRyan** [comment]
现在又有一个问题 新发布的版本网络请求获取到401 403这样的错误码 OnResponseListener依然调用的是onSuccess,原来代码是否更改过逻辑

**Comment by IrvingRyan** [comment]
新增加的问题 403 401等错误的网络调用的依然是OnResponseListener 的onSuccess

**Comment by yanzhenjie** [comment]
@IrvingRyan 是的，新版增加了400+和500+时可以获取到请求信息，其实400+和500+都是对于框架层都是成功的，只是业务逻辑是失败的，这个需要开发者判断一下，或者继承`RestRequest`等默认请求，在`parseResponse`中判断状态码，返回不同的数据，如何继承request自定义看下demo中的`FastJsonRequst`。
