### ISSUE TITLE
基于Okhttp的 不能同时添加两个请求头

### ISSUE THREAD

**Issue by pluszhou** [yanzhenjie/NoHttp#85]
`
    public NoHttpGsonRequest(String url, RequestMethod requestMethod, Class<T> clazz) {
        super(url, requestMethod);
        setRetryCount(5);
        this.clazz = clazz;
        addHeader(Constants.spToken, SpUtile.getInstance().getString(Constants.spToken, ""));
        addHeader(Constants.spRegion, "济南");
    }
`
请求时只有第二个Header,没有第一Header

**Comment by yanzhenjie** [comment]
应该不会，add的话会累加的，不论key是否重复，你可以打开调试模式查看提交的header：
```java
Logger.setDebug(true);
```
