### ISSUE TITLE
取消请求，请求还是会继续，只是不走回调方法？

### ISSUE THREAD

**Issue by leestars** [yanzhenjie/NoHttp#86]
在我的理解，取消请求就是中断这个请求了
D/NoHttpSample: --------------Request finish--------------
D/NoHttpSample: http://api.nohttp.net/method?name=yanzhenjie&pwd=123&userAge=20&userSex=1 finish, but it's canceled.

**Comment by yanzhenjie** [comment]
对的，目前发起的请求是无法中断的，我还没有想出一个特别好的方法，如果你有思路可以提供给我一下。
