### ISSUE TITLE
有时候下载不全，显示.nohttp文件？

### ISSUE THREAD

**Issue by sailorr** [yanzhenjie/NoHttp#88]
下载TXT文件，有时会下载***.txt.nohttp文件是什么原因？？

**Comment by yanzhenjie** [comment]
哪个版本的NoHttp？  你可以升级到最新版试试看。

**Comment by sailorr** [comment]
3.6的版本。
报java.lang.ArithmeticException: divide by zero ，或这server 416的错误
我在downloaderror  重新启动下载了。

**Comment by yanzhenjie** [comment]
服务器不支持断点续传吧？NoHttp还没有3.6版本呢，你说的是OkHttp？你看看NoHttp版本，和Github主页是否一致，新版兼容了服务器这个416的情况。

**Comment by sailorr** [comment]
谢谢
