### ISSUE TITLE
好像不能清除缓存啊

### ISSUE THREAD

**Issue by Invinciblelee** [yanzhenjie/NoHttp#9]

**Comment by yanzhenjie** [comment]
@q1466215893 
`DiskCacheStore.INSTANCE.remove(String)`删除某一个指定Key的缓存，Key默认是Url，Key可以通过`Request.setCacheKey`来改变。
`DiskCacheStore.INSTANCE.clear()`清除所有缓存。

**Comment by Lsy1992** [comment]
获取缓存文件大小呢？

**Comment by yanzhenjie** [comment]
@Lsy1992 没有缓存文件这个概念喔

**Comment by Lsy1992** [comment]
额，我是这个意思，就好比你使用微博的“清除缓存”功能一样，它会显示出缓存的大小例如：（123M）这样，不知道我们这个库能否取到缓存大小？

**Comment by yanzhenjie** [comment]
@Lsy1992 这个目前没有，如果开启了缓存的话，数据是保存在数据库的。我在下个版本加一下，不过这个影响不大应该。

**Comment by fairytale2016** [comment]
查看手机上项目database文件夹里面，既然在数据库，就可以自己获取文件大小

**Comment by caiyoufei** [comment]
可以设置缓存时间么？

**Comment by yanzhenjie** [comment]
@fairytale2016  @Lsy1992 新版的NoHttp支持设置缓存到数据库、SD卡、SD卡需要制定文件夹位置，你就可以获取到缓存文件大小了。
关于缓存时间的问题请看这个[#55](https://github.com/yanzhenjie/NoHttp/issues/55)
