### ISSUE TITLE
setConnectTimeout() setReadTimeou()无效

### ISSUE THREAD

**Issue by chenglove1201** [yanzhenjie/NoHttp#93]
这两个方法怎么无效，默认时也不是10秒，不管怎么设置这个参数，就算用默认的，也是30秒的超时时间

**Comment by yanzhenjie** [comment]
看一下我在知乎写的这个答案：[HTTP 在什么情况下会请求超时](https://www.zhihu.com/question/21609463/answer/160100810)。
