### ISSUE TITLE
Using NoHttp in MVP or Fragment

### ISSUE THREAD

**Issue by LittleWaver** [yanzhenjie/NoHttp#96]
严大，在MVP模式中使用NoHttp时，由于NoHttp的使用需要Activity的request()方法，需要通过View层传递activity的context到Persenter层，再传递到Model层。请问哈严大，有独立于context（Activity或者Fragment）方式使用NoHttp的方案吗

**Comment by yanzhenjie** [comment]
其实nohttp并没有限制你在哪里使用，你说的context只是为了在listener中显示dialog吧，这一点可以不用参考demo的封装，不要在model中显示dialog即可。本周末会推出全新的rxjava的使用方式，到时候也可以试试。

**Comment by LittleWaver** [comment]
谢谢严大！
