### ISSUE TITLE
下载提示存储空间不足但有空间。

### ISSUE THREAD

**Issue by OaixGnauh** [yanzhenjie/NoHttp#98]
感谢严大回复。
当前使用NoHttp 1.1.2，设备为iTop4412 开发板。
下载文件失败，StorageSpaceNotEnoughError ：The folder is not enough space to save the downloaded file: /mnt/sdcard/HeServer/UpVersion/. 但实际有足够的存储空间。

![Image of Yaktocat](http://ognv98dxj.bkt.clouddn.com/QQ%E6%88%AA%E5%9B%BE20170527143628.png)
![Image of Yaktocat](http://ognv98dxj.bkt.clouddn.com/QQ%E6%88%AA%E5%9B%BE20170527143648.png)

另：NoHttp1.1.0 没有该错误。

**Comment by liajt** [comment]
我也遇到了一样的问题，下载空间不足，但实际上是充足的

**Comment by yanzhenjie** [comment]
@liajt 试试1.1.21，修复了这个问题。

**Comment by liajt** [comment]
@yanzhenjie 1.1.21还是有这个问题：下载大文件800M，已经下载500M，空间还剩600M，这个时候就下载不了， 报空间不足。理想中只需要还有300M的空间，就应该可以把剩下的文件下完，但还有600M却下不完。

**Comment by onion2333** [comment]
我也遇到了这个问题，目前来说只有部分机型有这个问题

**Comment by onion2333** [comment]
我查看了一下这个问题，是因为你的IOUtils这个工具类里，getDirSize这个方法的一个问题。在Android4.2及以下版本时会调用stat.getBlockSize() * stat.getAvailableBlocks()获取数据，但是因为stat.getAvailableBlocks()这个方法返回的是int类型，使用弃用方法在内存大时容易造成内存溢出，导致得到的值为负值，本质原因就是赋为int超出其取值范围了。建议强转一下就ok了，stat.getBlockSize() * Long.valueOf(stat.getAvailableBlocks())，希望下个版本能修正。

**Comment by yanzhenjie** [comment]
感谢反馈，会在新版中修复。

**Comment by RockVampire** [comment]
遇到同样的问题了，新版还没有修复么

**Comment by zhuminjunivan** [comment]
遇到该问题 还没有新版本么

**Comment by zhuminjunivan** [comment]
1.1.4 未解决该问题

**Comment by yanzhenjie** [comment]
刚刚发布了1.1.5版本，根据@onion2333 的方案做了处理，修复了这个问题，谢谢大家反馈。
